### ISSUE TITLE
texterify-ios-sdk: could not download new strings

### ISSUE THREAD

**Issue by ljaniszewski00** [txty-io/deprecated-txty-ios#3]
While initializing TexterifyManager object with 
`TexterifyManager(baseUrl: "https://texterify.mydomain.io",
                                         projectId: {projectId},
                                         exportConfigId: {exportConfigId})` 

I get following output:

texterify-ios-sdk: download initializing 
2022-10-30 20:19:35.717233+0100 SwiftfulShopping[83793:2947530] Connection 4: received failure notification
2022-10-30 20:19:35.717290+0100 SwiftfulShopping[83793:2947530] Connection 4: failed to connect 12:8, reason -1
2022-10-30 20:19:35.717345+0100 SwiftfulShopping[83793:2947530] Connection 4: encountered error(12:8)
2022-10-30 20:19:35.717973+0100 SwiftfulShopping[83793:2947530] Task <DDFFFA41-728D-47E2-B894-DE9834E7083D>.<1> HTTP load failed, 0/0 bytes (error code: -1003 [12:8])
2022-10-30 20:19:35.724137+0100 SwiftfulShopping[83793:2947529] Task <DDFFFA41-728D-47E2-B894-DE9834E7083D>.<1> finished with error [-1003] Error Domain=NSURLErrorDomain Code=-1003 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=8, NSUnderlyingError=0x6000020fc630 {Error Domain=kCFErrorDomainCFNetwork Code=-1003 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0, _kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <DDFFFA41-728D-47E2-B894-DE9834E7083D>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <DDFFFA41-728D-47E2-B894-DE9834E7083D>.<1>"
), NSLocalizedDescription=Could not connect to the server., 
NSErrorFailingURLStringKey=https://api/v1/projects/{projectId}/export_configs/{exportConfigId}/release?locale=pl-US, 
NSErrorFailingURLKey=https://api/v1/projects/{projectId}/export_configs/{exportConfigId}/release?locale=pl-US, _kCFStreamErrorDomainKey=12}
💬texterify-ios-sdk: could not download new strings

I replace my real projectId and exportConfigId values with {projectId} and {exportConfigId} for security reasons. In the actual output they are correct values from Texterify website.
My app supports: english (default language), polish, german, spanish, french, czech

Would be very happy for some help.

**Comment by chrztoph** [comment]
Hey, could you try replacing the example domain of `https://texterify.mydomain.io` with `https://texterify.mydomain.io` if using the cloud service?

**Comment by ljaniszewskiPerfectGym** [comment]
@chrztoph If I were meant to make this change in constructor of TexterifyManager so that `baseURL` parameter would be `"https://app.texterify.com"` then it did not make any change, the problem still occurs
What I noticed in the console output I posted above is that `locale=pl-US` in both `NSErrorFailingURL`. Can't it be the problem?

**Comment by ljaniszewski00** [comment]
@chrztoph If I were meant to make this change in constructor of TexterifyManager so that baseURL parameter would be "https://app.texterify.com" then it did not make any change, the problem still occurs
What I noticed in the console output I posted above is that locale=pl-US in both NSErrorFailingURL. Can't it be the problem?

**Comment by chrztoph** [comment]
The error above `Could not connect to the server` indicated that the server could not be reached. `https://api/v1/projects/%7BprojectId%7D/export_configs/%7BexportConfigId%7D/release?locale=pl-US` is not a valid URL as it is missing the `app.texterify.com` part at the beginning. Could you share your initialization code once more with the updated `baseUrl`?

**Comment by ljaniszewski00** [comment]
@chrztoph This is my `AppDelegate` class

```
class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        
        // Initializing Firebase
        FirebaseApp.configure()
        
        ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
        
        // Initializing Texterify
        let localizer = TexterifyManager(baseUrl: "https://app.texterify.com",
                                         projectId: {projectId},
                                         exportConfigId: {exportConfigId})
        localizer.getUpdatedStrings { _ in }
        
        return true
    }
    
    func application(_ app: UIApplication,
                     open url: URL,
                     options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        return ApplicationDelegate.shared.application(app, open: url, options: options)
    }
}
```

**Comment by pagedimka** [comment]
Is there a solution to this problem? I also experience such messages in the console

**Comment by pagedimka** [comment]
is there any support here? how to solve this problem?

**Comment by chrztoph** [comment]
Hey, the problem ist that the `baseUrl` should be written as:

```
baseUrl: "app.texterify.com"
````

without the leading `https://`. This was an issue within the `README`.

Also make sure to generate a new OTA release, because there was an issue with release generation.

Let me know if it works now. Sorry for the troubles.

**Comment by pagedimka** [comment]
Yes, now the error with the base URL is not displayed, but there are other notifications in the console:
```
 texterify-ios-sdk: parsing release file
 texterify-ios-sdk: error while decoding release file
```

**Comment by chrztoph** [comment]
Have you created a new release file?

**Comment by pagedimka** [comment]
I re-uploaded the sdk, maybe I'm doing something wrong in texterify itself?  I added a default language and 1 more language to translate into.  Do you have a more detailed guide for configuring Swift?

**Comment by pagedimka** [comment]
Yes it worked, thank you very much! I have another question, now I'm using this in the trial period, and the Over the air translations feature is only available in the Business plan?

**Comment by pagedimka** [comment]
I don't have any errors in the console, but I don't get the translation over the air, I can send you screenshots of how the export configuration is configured, maybe I configured something wrong ?

**Comment by chrztoph** [comment]
Yes, it is part of the business plan as we are hosting the files for delivery. If you have any special requests please contact us via support@texterify.com.

Whenever you are changing your translations you need to create a new release to create a snapshot of your translations. Also keep in mind the description from the `README`:

```
All the UI elements that are loaded after the download is done will show the changes immediately or after app restart.
```

I don't think the export config is relevant for debugging this issue.
